/* eslint-disable */
// @ts-nocheck
// AUTO-GENERATED by tauri-specta — do not edit by hand.
// Regenerate with `cargo xtask gen-bindings`.

// This file was generated by [tauri-specta](https://github.com/oscartbeaumont/tauri-specta). Do not edit this file manually.

/** user-defined commands **/


export const commands = {
async init() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("init") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async askpassRespond(response: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("askpass_respond", { response }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async ping(name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping", { name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeModal() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_modal") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async confirmAction() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("confirm_action") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dialog(dialog: DialogKind, paneHandle: PaneHandle | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dialog", { dialog, paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async destroyWindow() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("destroy_window") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setWindowTitle(title: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_window_title", { title }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async zoom(factor: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("zoom", { factor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancel(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async navigate(paneHandle: PaneHandle, path: string, exact: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("navigate", { paneHandle, path, exact }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async enter(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("enter", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async focus(paneHandle: PaneHandle, filename: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("focus", { paneHandle, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSorting(paneHandle: PaneHandle, sorting: Sorting) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_sorting", { paneHandle, sorting }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async toggleSelected(paneHandle: PaneHandle, filename: string | null, focusNext: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("toggle_selected", { paneHandle, filename, focusNext }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async selectRange(paneHandle: PaneHandle, filename: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("select_range", { paneHandle, filename }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelection(paneHandle: PaneHandle, selected: string[], focused: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selection", { paneHandle, selected, focused }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setSelectionByIndices(paneHandle: PaneHandle, start: number, end: number, additive: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_selection_by_indices", { paneHandle, start, end, additive }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async endDragSelection(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("end_drag_selection", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async relativeJump(paneHandle: PaneHandle, offset: number, withSelection: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("relative_jump", { paneHandle, offset, withSelection }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setViewport(paneHandle: PaneHandle, firstVisible: number, visibleCount: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_viewport", { paneHandle, firstVisible, visibleCount }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setFilter(paneHandle: PaneHandle, filter: string | null, mode: FilterMode | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_filter", { paneHandle, filter, mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async createDirectory(paneHandle: PaneHandle | null, path: VfsPath, name: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("create_directory", { paneHandle, path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async touchFile(paneHandle: PaneHandle | null, path: VfsPath, name: string, openEditor: boolean | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("touch_file", { paneHandle, path, name, openEditor }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async rename(paneHandle: PaneHandle | null, basePath: VfsPath, oldName: string, newName: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("rename", { paneHandle, basePath, oldName, newName }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setMetadata(paneHandle: PaneHandle | null, paths: VfsPath[], modeSet: number, modeClear: number, uid: number | null, gid: number | null, recursive: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_metadata", { paneHandle, paths, modeSet, modeClear, uid, gid, recursive }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startOperation(request: OperationRequest) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_operation", { request }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startCopyMove(kind: string, sources: VfsPath[], destination: VfsPath, options: CopyOptions) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_copy_move", { kind, sources, destination, options }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelOperation(operationId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_operation", { operationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resolveIssue(operationId: number, issueId: number, action: IssueAction, applyToAll: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("resolve_issue", { operationId, issueId, action, applyToAll }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async dismissOperation(operationId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("dismiss_operation", { operationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async backgroundOperation(operationId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("background_operation", { operationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async foregroundOperation(operationId: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("foreground_operation", { operationId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async fileDetails(path: VfsPath) : Promise<Result<FileDetails, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("file_details", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFileRange(path: VfsPath, offset: number, length: number) : Promise<Result<FileChunk, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file_range", { path, offset, length }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async readFile(path: VfsPath, maxSize: number) : Promise<Result<number[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("read_file", { path, maxSize }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async writeFile(path: VfsPath, data: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("write_file", { path, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setViewerMode(mode: ViewerMode) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_viewer_mode", { mode }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pingViewer() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping_viewer") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Copy a byte range from a file to the system clipboard.
 */
async copyViewerRange(path: VfsPath, offset: number, length: number, format: CopyFormat) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("copy_viewer_range", { path, offset, length, format }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async findInViewer(path: VfsPath, offset: number, pattern: SearchPattern, maxLength: number) : Promise<Result<SearchMatch | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("find_in_viewer", { path, offset, pattern, maxLength }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEditorLanguage(language: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_editor_language", { language }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setEditorWrap(wrap: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_editor_wrap", { wrap }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async pingEditor() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("ping_editor") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async reconnect() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reconnect") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectTarget(paneHandle: PaneHandle, kind: ConnectionKind, openIn: OpenIn) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_target", { paneHandle, kind, openIn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverSshHosts(openIn: OpenIn) : Promise<Result<DiscoveryResult<SshHostEntry>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_ssh_hosts", { openIn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverDockerContainers(openIn: OpenIn) : Promise<Result<DiscoveryResult<ContainerEntry>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_docker_containers", { openIn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverPodmanContainers(openIn: OpenIn) : Promise<Result<DiscoveryResult<ContainerEntry>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_podman_containers", { openIn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverKubeContexts(openIn: OpenIn) : Promise<Result<DiscoveryResult<string>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_kube_contexts", { openIn }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async discoverKubePods(openIn: OpenIn, context: string | null, namespace: string | null) : Promise<Result<DiscoveryResult<KubePodEntry>, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("discover_kube_pods", { openIn, context, namespace }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async switchVfs(paneHandle: PaneHandle, vfsId: VfsId | null, typeName: string, root: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("switch_vfs", { paneHandle, vfsId, typeName, root }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async unmountVfs(paneHandle: PaneHandle, vfsId: VfsId) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("unmount_vfs", { paneHandle, vfsId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalWrite(handle: TerminalHandle, data: number[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_write", { handle, data }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalResize(handle: TerminalHandle, rows: number, cols: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_resize", { handle, rows, cols }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async terminalFocus(handle: TerminalHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("terminal_focus", { handle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async closeTerminal(handle: TerminalHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("close_terminal", { handle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async activateTerminal(handle: TerminalHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("activate_terminal", { handle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async startDnd(paneHandle: PaneHandle, files: DndFile[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("start_dnd", { paneHandle, files }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cancelDnd() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cancel_dnd") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeDnd(destinationPane: PaneHandle, subdirectory: string | null, isMove: boolean) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_dnd", { destinationPane, subdirectory, isMove }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Handle files dropped from outside the app (OS file manager).
 * The dropped paths are host-local, so we need the host-local VFS to
 * construct VfsPaths from them.
 */
async externalDrop(paneHandle: PaneHandle, subdirectory: string | null, paths: string[]) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("external_drop", { paneHandle, subdirectory, paths }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPreferences() : Promise<Result<ResolvedPreferences, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_preferences") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updatePreference(key: string, value: JsonValue) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_preference", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetPreference(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_preference", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getPreferencesSchema() : Promise<Result<JsonValue, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_preferences_schema") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async setCommandKeybinding(commandId: string, newKey: string | null, newWhen: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("set_command_keybinding", { commandId, newKey, newWhen }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async resetCommandKeybinding(commandId: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("reset_command_keybinding", { commandId }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async openConfigFile() : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("open_config_file") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async getHotPaths() : Promise<Result<HotPathEntry[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("get_hot_paths") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addBookmark(path: string, name: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_bookmark", { path, name }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeBookmark(path: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_bookmark", { path }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async runUserCommand(paneHandle: PaneHandle, index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("run_user_command", { paneHandle, index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async executeUserCommand(paneHandle: PaneHandle, index: number, promptResponses: string[], confirmResponses: boolean[]) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("execute_user_command", { paneHandle, index, promptResponses, confirmResponses }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async addUserCommandEntry(entry: UserCommandEntry) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("add_user_command_entry", { entry }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async removeUserCommandEntry(index: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("remove_user_command_entry", { index }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async updateUserCommandEntry(index: number, entry: UserCommandEntry) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("update_user_command_entry", { index, entry }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdRename(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_rename", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdProperties(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_properties", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCreateDirectory(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_create_directory", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCreateFile(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_create_file", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCreateAndEdit(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_create_and_edit", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNavigate(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_navigate", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCopy(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_copy", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMove(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_move", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdConnectRemote(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_connect_remote", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSelectVfs(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_select_vfs", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCommandPalette(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_command_palette", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdUserCommands(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_user_commands", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdDirectoryProperties(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_directory_properties", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdOpenSettings(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_open_settings", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNewWindow(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_new_window", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdToggleHidden(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_toggle_hidden", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCloseWindow(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_close_window", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdView(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_view", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdEdit(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_edit", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdOpen(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_open", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdOpenArchive(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_open_archive", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdOpenFolder(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_open_folder", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdFollowSymlink(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_follow_symlink", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNavigateBack(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_navigate_back", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNavigateForward(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_navigate_forward", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdHistoryBack(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_history_back", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdHistoryForward(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_history_forward", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdHistory(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_history", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async navigateHistory(paneHandle: PaneHandle, targetIndex: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("navigate_history", { paneHandle, targetIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Remove an entry from a pane's navigation history. Used by the persistent
 * history dialog (the alt-tab overlay shows entries read-only). The
 * modal is *not* closed — the dialog state is refreshed in place by
 * rebuilding the entries list, so the user can keep deleting.
 */
async deleteHistoryEntry(paneHandle: PaneHandle, targetIndex: number) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("delete_history_entry", { paneHandle, targetIndex }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAsOtherPane(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_as_other_pane", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdOpenInLeftPane(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_open_in_left_pane", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdOpenInRightPane(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_open_in_right_pane", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSelectAll(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_select_all", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdDeselectAll(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_deselect_all", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCopyToClipboard(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_copy_to_clipboard", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdPasteFromClipboard(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_paste_from_clipboard", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSendToTerminal(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_send_to_terminal", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdToggleTerminalPanel(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_toggle_terminal_panel", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdFocusPanes(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_focus_panes", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdFocusTerminal(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_focus_terminal", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdCreateTerminal(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_create_terminal", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdNextTerminal(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_next_terminal", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdPrevTerminal(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_prev_terminal", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdOpenElevated(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_open_elevated", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Top-level "Connect to WSL Distribution..." command. With one distro,
 * connect straight away; with several, open the picker; with none, error.
 */
async cmdConnectWsl(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_connect_wsl", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Picked a distro in the WSL picker — open a session to it.
 */
async connectWslDistro(distro: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_wsl_distro", { distro }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdQuickConnect(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_quick_connect", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMountS3(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_mount_s3", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mountS3(paneHandle: PaneHandle, region: string | null, bucket: string | null, credentials: S3Credentials) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mount_s3", { paneHandle, region, bucket, credentials }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMountSftp(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_mount_sftp", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdMountK8s(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_mount_k8s", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdUnmountVfs(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_unmount_vfs", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mountSftp(paneHandle: PaneHandle, host: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mount_sftp", { paneHandle, host }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async mountK8s(paneHandle: PaneHandle, context: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mount_k8s", { paneHandle, context }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Submit handler for the search dialog. Builds a `SearchVfs` rooted at
 * `root` with the supplied parameters and navigates the pane to its
 * mount root. `name_pattern` is a glob (`*.rs`, `Cargo.*`, …);
 * `content_*` together optionally specify a content match (one of
 * literal substring or regex). Empty strings are treated as "not set".
 */
async mountSearch(paneHandle: PaneHandle, root: VfsPath, namePattern: string | null, contentPattern: string | null, contentIsRegex: boolean, caseSensitive: boolean, followSymlinks: boolean) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("mount_search", { paneHandle, root, namePattern, contentPattern, contentIsRegex, caseSensitive, followSymlinks }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * cmd+f. Unlike the other dialog shims this one isn't built with
 * `cmd_dialog!`: if the active pane's VFS opts out of recursive search
 * (`VfsDescriptor::can_search`), we transparently fall back to opening
 * the in-pane quick filter — the same effect as pressing `/`.
 */
async cmdStartSearch(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_start_search", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdHotPaths(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_hot_paths", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAddBookmark(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_add_bookmark", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdOpenConfigFile(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_open_config_file", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdRefresh(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_refresh", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdDeleteSelected(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_delete_selected", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Show the next operation in foreground, cycling by op id. If an op is
 * currently foregrounded, send it to the background first and surface the
 * next one (wrapping). If none is foregrounded, surface the oldest
 * backgrounded op. No-op when no operations exist.
 */
async cmdShowNextOperation(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_show_next_operation", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdDebug(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_debug", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
/**
 * Kick off a synthetic long-running operation. Reachable only from the
 * Debug modal, itself unavailable outside `debug_assertions` builds.
 */
async cmdDebugRunTestOperation(durationSeconds: number) : Promise<Result<number, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_debug_run_test_operation", { durationSeconds }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdConnectionLog(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_connection_log", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdAbout(paneHandle: PaneHandle) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_about", { paneHandle }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async keychainGet(key: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("keychain_get", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async keychainSet(key: string, value: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("keychain_set", { key, value }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async keychainDelete(key: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("keychain_delete", { key }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdListConnections() : Promise<Result<ConnectionProfile[], string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_list_connections") };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdSaveConnection(profile: ConnectionProfile, secret: string | null) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_save_connection", { profile, secret }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdDeleteConnection(id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_delete_connection", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async cmdGetConnectionSecret(id: string) : Promise<Result<string | null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("cmd_get_connection_secret", { id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
},
async connectProfile(paneHandle: PaneHandle, id: string) : Promise<Result<null, string>> {
    try {
    return { status: "ok", data: await TAURI_INVOKE("connect_profile", { paneHandle, id }) };
} catch (e) {
    if(e instanceof Error) throw e;
    else return { status: "error", error: e  as any };
}
}
}

/** user-defined events **/



/** user-defined constants **/



/** user-defined types **/

/**
 * User-facing preferences that can be set in settings.toml.
 * 
 * Serde defaults ensure every field has a compiled-in default. The JSON Schema
 * is derived via `schemars` so the frontend settings editor can be generated
 * automatically.
 */
export type AppPreferences = { appearance?: AppearancePreferences; behavior?: BehaviorPreferences; hot_paths?: HotPathsPreferences; environment?: EnvironmentPreferences }
export type AppearancePreferences = { 
/**
 * Show hidden files by default when opening a new window.
 */
show_hidden: boolean; 
/**
 * Always show folders before files regardless of sort order.
 */
folders_first: boolean; 
/**
 * Show the F-key command bar at the bottom of the window.
 */
show_command_bar: boolean; 
/**
 * Show the top bar (path breadcrumbs, VFS selector, free space) on each pane.
 */
show_pane_header: boolean; 
/**
 * Show the status bar (file/directory counts, selection size) at the bottom of each pane.
 */
show_pane_status: boolean; 
/**
 * Color theme: "system" follows OS preference, or force "light" / "dark".
 */
theme: ThemeMode; 
/**
 * Visible columns and their order.
 */
columns: string[] }
export type AskpassPrompt = { prompt: string; is_secret: boolean }
export type BehaviorPreferences = { 
/**
 * Ask for confirmation before deleting files.
 */
confirm_delete: boolean; 
/**
 * Keep terminal tab open after the shell process exits.
 */
keep_terminal_open: boolean; 
/**
 * Keep completed/cancelled operations visible in the operations panel.
 */
keep_finished_operations: boolean; 
/**
 * Use incremental quick-search when typing in a file pane. When disabled,
 * typing opens the regex filter directly.
 */
quick_search: boolean; 
/**
 * In remote (SSH) sessions, expose the local filesystem to the remote
 * host so it can be browsed alongside remote files. Disable this if the
 * remote host is untrusted.
 */
expose_local_fs: boolean; 
/**
 * Default sort order for new panes.
 */
default_sort: DefaultSort; 
/**
 * Maximum number of entries kept in each pane's navigation history.
 * `0` means unlimited (entries accumulate for the lifetime of the
 * session). When the cap is reached, the oldest entries roll out as
 * new ones are pushed.
 */
history_retention: number }
/**
 * A single `[[bookmark]]` entry in the TOML file.
 */
export type BookmarkEntry = { path: string; name?: string | null }
export type Breadcrumb = { label: string; nav_path: string }
/**
 * Command metadata for the command palette.
 */
export type CommandInfo = { id: string; name: string; short_name: string | null; category: string; shortcut: string | null; shortcut_display: string[]; needs_pane: boolean; 
/**
 * Keybinding *dispatch context* (`pane_focused` / `terminal_focused` /
 * unset = global). For user commands this is hard-coded to
 * `pane_focused`. For built-ins it reflects the resolved binding's
 * `when`. Distinct from `applies_to`, which is the user-command
 * run-filter.
 */
when: string | null; 
/**
 * User-command run filter (`file` / `directory` / `selection` / unset =
 * any). Only set for user commands; always `None` for built-ins.
 */
applies_to: string | null; 
/**
 * The compiled-in default key for this command, if any. Useful for the
 * keybindings editor to display "Default: …" hints and offer Reset.
 */
default_key: string | null; 
/**
 * The compiled-in default dispatch context for this command, if any.
 */
default_when: string | null; 
/**
 * True when the resolved keybinding for this command differs from its
 * compiled-in default (either remapped by the user, disabled, or its
 * default slot has been usurped by another command). Only meaningful
 * for built-ins; always `false` for user commands.
 */
user_overridden: boolean }
export type ConfirmAction = { type: "delete_selected"; paths: VfsPath[] }
export type ConnectionKind = { type: "s3"; region?: string | null; bucket?: string | null; endpoint_url?: string | null; credential_mode?: string; profile?: string | null; role_arn?: string | null; external_id?: string | null } | { type: "sftp"; host: string } | { type: "ssh"; host: string; forward_agent?: boolean } | { type: "docker"; container: string; user?: string | null; bootstrapless?: boolean } | { type: "podman"; container: string; user?: string | null; bootstrapless?: boolean } | { type: "kube"; context?: string | null; namespace?: string | null; pod: string; container?: string | null } | { type: "custom"; command: string; skip_bootstrap?: boolean }
/**
 * A saved connection profile. Secrets are stored in the system keychain,
 * not in this struct or the connections file.
 */
export type ConnectionProfile = ({ type: "s3"; region?: string | null; bucket?: string | null; endpoint_url?: string | null; credential_mode?: string; profile?: string | null; role_arn?: string | null; external_id?: string | null } | { type: "sftp"; host: string } | { type: "ssh"; host: string; forward_agent?: boolean } | { type: "docker"; container: string; user?: string | null; bootstrapless?: boolean } | { type: "podman"; container: string; user?: string | null; bootstrapless?: boolean } | { type: "kube"; context?: string | null; namespace?: string | null; pod: string; container?: string | null } | { type: "custom"; command: string; skip_bootstrap?: boolean }) & { id: string; name: string; 
/**
 * How a spawn-style connection opens: a full remote session in a new
 * window, or an FS-only agent mount in the active pane. Ignored for
 * VFS kinds (S3/SFTP), which are always pane mounts.
 */
open_in?: OpenIn }
export type ConnectionStatus = { status: "connecting"; message: string; log: string[] } | { status: "connected"; log: string[] } | { status: "disconnected"; log: string[]; error: string } | { status: "failed"; log: string[]; error: string }
export type ContainerEntry = { id: string; name: string; image: string; state: string }
/**
 * How to render a byte range when copying to the clipboard.
 */
export type CopyFormat = 
/**
 * UTF-8 lossy decode of the bytes.
 */
"text" | 
/**
 * Space-separated uppercase hex (`AB CD EF`).
 */
"hex" | 
/**
 * Printable ASCII (0x20–0x7e); other bytes become `.`.
 */
"ascii"
export type CopyOptions = { preserve_timestamps: boolean; preserve_owner: boolean; preserve_group: boolean; create_symlink: boolean }
export type DefaultSort = { key: DefaultSortKey; ascending: boolean }
export type DefaultSortKey = "name" | "extension" | "size" | "modified" | "accessed" | "created"
/**
 * Every dialog the host can open. Serialized as snake_case so the frontend
 * can keep sending string literals like `"navigate"` / `"mount_s3"` over
 * IPC — but a typo on either side now fails to compile rather than producing
 * `Error::Custom("unknown dialog: …")` at runtime.
 */
export type DialogKind = "navigate" | "create_directory" | "create_file" | "create_and_edit" | "directory_properties" | "properties" | "rename" | "copy" | "move" | "connect_remote" | "mount_sftp" | "mount_s3" | "search" | "mount_k8s" | "quick_connect" | "select_vfs" | "history_back" | "history_forward" | "history" | "command_palette" | "user_commands" | "hot_paths" | "settings" | "debug" | "connection_log" | "about"
export type DiscoveryResult<T> = { items: T[]; 
/**
 * Best-effort failure note. When present, the dialog should show this
 * dimmed under the combo-box instead of an empty list.
 */
warning: string | null }
export type DisplayOptionsInner = { show_hidden: boolean; active_pane: PaneHandle; active_terminal: TerminalHandle | null; panes_focused: boolean; terminal_panel_visible: boolean }
export type DndData = { source_pane: PaneHandle; files: DndFile[] }
export type DndFile = { name: string; is_dir: boolean }
export type EnvironmentPreferences = { 
/**
 * Directories to prepend to `PATH` at startup. Useful on macOS / GNOME
 * where GUI apps don't inherit the user's shell `PATH`, so subprocesses
 * like `docker` / `kubectl` / `podman` can't be found at their usual
 * install locations. Leading `~` expands to the user's home directory.
 * Non-existent entries are silently skipped.
 */
extra_path: string[] }
export type File = { name: string; size: number | null; is_dir: boolean; is_hidden: boolean; is_symlink: boolean; 
/**
 * Raw link target as reported by the source FS. A string, not a path
 * type: it may be relative (`../x`) or otherwise un-normalizable, and
 * it crosses the agent↔host RPC boundary — no `std::path` there, its
 * meaning belongs to the source OS, not the receiver's.
 */
symlink_target: string | null; user: UserGroup | null; group: UserGroup | null; mode: Mode | null; modified: number | null; accessed: number | null; created: number | null; 
/**
 * Directory-scoped identifier. When `None`, `name` is used as the
 * identifier — the common case. Set explicitly by synthetic VFSes
 * (e.g. flat search results, where `name` is the basename for display
 * but multiple entries can share it). See `File::key()`.
 */
key: string | null; 
/**
 * Underlying source path for entries that are virtual references to a
 * real file in another VFS — e.g. a search result. Frontend uses this
 * for the "where from" secondary display; backend treats it as
 * informational (the operative redirect is in `VfsRegistry`, see
 * `Vfs::redirect_target`).
 */
source: VfsPath | null }
export type FileChunk = { data: number[]; offset: number; total_size: number }
export type FileDetails = { size: number; mime_type: string | null; is_dir: boolean; is_symlink: boolean; 
/**
 * Raw link target as reported by the source FS (see `File::symlink_target`).
 */
symlink_target: string | null; user: UserGroup | null; group: UserGroup | null; mode: Mode | null; modified: number | null; accessed: number | null; created: number | null }
export type FileList = { path: VfsPath; fs_stats: FsStats | null; files: File[]; 
/**
 * Set when the underlying VFS reports that the listing is
 * intrinsically incomplete (e.g. a SearchVfs whose walker was
 * cancelled). Surfaces in the pane status bar as `(partial)` and
 * is sticky across navigations into the same VFS.
 */
partial: boolean }
export type FilterMode = "quick_search" | "filter"
export type FsStats = { free_bytes: number; available_bytes: number; total_bytes: number }
/**
 * Frontend-visible view of a single history entry. Sent via the
 * HistoryNavigator modal. `is_alive` reflects whether the entry's VFS is
 * currently mounted; the overlay uses this to grey out & skip dead entries.
 * `arrived_at` is the user's original arrival time at this path expressed
 * as Unix milliseconds; the overlay groups adjacent entries into time
 * buckets using these values.
 */
export type HistoryEntryView = { path: VfsPath; vfs_display_name: string; display_path: string; is_alive: boolean; arrived_at: number }
export type HotPathCategory = "UserBookmark" | "StandardFolder" | "Bookmark" | "Mount" | "RecentFolder"
export type HotPathEntry = { path: VfsPath; 
/**
 * User-facing rendering of `path` (via the VFS descriptor). The
 * provider can't format — it has no mounted-VFS context — so it
 * leaves this empty; the host fills it in `get_hot_paths`.
 */
display_path: string; name: string | null; category: HotPathCategory }
export type HotPathsPreferences = { 
/**
 * Show standard folders (Home, Downloads, Documents, etc.)
 */
standard_folders: boolean; 
/**
 * Show system bookmarks (GTK bookmarks on Linux)
 */
system_bookmarks: boolean; 
/**
 * Show mounted volumes and removable media
 */
mounts: boolean; 
/**
 * Show recently visited folders
 */
recent_folders: boolean }
export type IssueAction = "skip" | "overwrite" | "retry"
export type JsonValue = null | boolean | number | string | JsonValue[] | Partial<{ [key in string]: JsonValue }>
export type KubePodEntry = { namespace: string; name: string; containers: string[] }
export type ModalContext = { pane_handle: PaneHandle | null }
export type ModalData = ({ type: "create_directory"; data: { path: VfsPath } } | { type: "create_file"; data: { path: VfsPath; open_editor: boolean } } | { type: "properties"; data: { paths: VfsPath[]; name: string; size: number | null; is_dir: boolean; is_symlink: boolean; symlink_target: string | null; 
/**
 * Whether the VFS supports metadata changes (chmod/chown)
 */
can_set_metadata: boolean; 
/**
 * Bits that are ON in all selected files
 */
mode_set: number; 
/**
 * Bits that are OFF in all selected files
 */
mode_clear: number; 
/**
 * Whether any file has a mode at all
 */
has_mode: boolean; owner: UserGroup | null; group: UserGroup | null; 
/**
 * Owner UID (resolved from name if needed)
 */
owner_id: number | null; 
/**
 * Group GID (resolved from name if needed)
 */
group_id: number | null; modified: number | null; accessed: number | null; created: number | null } } | { type: "navigate"; data: { path: VfsPath; display_path: string } } | { type: "rename"; data: { base_path: VfsPath; name: string } } | { type: "copy_move"; data: { kind: string; sources: VfsPath[]; destination: VfsPath; display_destination: string; summary: string } } | { type: "connect_remote"; data: { 
/**
 * Pre-populated transport for the dialog. Empty `Ssh { host: "" }`
 * when opened cold from the palette.
 */
initial: ConnectionKind } } | { type: "mount_sftp"; data: { host: string } } | { type: "mount_s3" } | 
/**
 * Recursive-search dialog. Opened from a pane to mount a `SearchVfs`
 * rooted at `path`. The pane navigates to the mount root on submit.
 */
{ type: "search"; data: { 
/**
 * Search root, captured from the source pane at dialog-open time.
 */
path: VfsPath; 
/**
 * Pre-rendered display label for the root (so the dialog can
 * show "Search in /home/foo" without re-resolving).
 */
display_path: string } } | { type: "mount_k8s"; data: { k8s_context: string } } | { type: "quick_connect"; data: { connections: ConnectionProfile[] } } | { type: "select_vfs"; data: { targets: VfsTarget[] } } | { type: "select_wsl_distro"; data: { distros: WslDistro[] } } | { type: "history_navigator"; data: { entries: HistoryEntryView[]; current_index: number; 
/**
 * Direction of the keypress that opened the overlay: -1 for back,
 * +1 for forward. The overlay uses this to set the initial preview
 * (one step in that direction, skipping dead entries).
 */
initial_direction: number; 
/**
 * When true, the overlay is opened as a persistent dialog: it stays
 * open until explicitly dismissed (Esc / outside-click), Alt-up does
 * not commit, blur does not abort, and per-entry delete buttons are
 * shown. When false, the overlay behaves alt-tab style (the default
 * alt-held mode).
 */
persistent: boolean } } | { type: "command_palette"; data: { category_filter: string | null } } | { type: "hot_paths" } | { type: "settings" } | { type: "confirm"; data: { message: string; action: ConfirmAction } } | { type: "user_command_input"; data: { command_index: number; command_title: string; prompts: UserCommandPrompt[]; confirms: string[] } } | { type: "debug" } | { type: "connection_log" } | { type: "about"; data: { version: string; git_revision: string | null; target_triple: string } }) & { context: ModalContext }
export type ModalDataKind = { type: "create_directory"; data: { path: VfsPath } } | { type: "create_file"; data: { path: VfsPath; open_editor: boolean } } | { type: "properties"; data: { paths: VfsPath[]; name: string; size: number | null; is_dir: boolean; is_symlink: boolean; symlink_target: string | null; 
/**
 * Whether the VFS supports metadata changes (chmod/chown)
 */
can_set_metadata: boolean; 
/**
 * Bits that are ON in all selected files
 */
mode_set: number; 
/**
 * Bits that are OFF in all selected files
 */
mode_clear: number; 
/**
 * Whether any file has a mode at all
 */
has_mode: boolean; owner: UserGroup | null; group: UserGroup | null; 
/**
 * Owner UID (resolved from name if needed)
 */
owner_id: number | null; 
/**
 * Group GID (resolved from name if needed)
 */
group_id: number | null; modified: number | null; accessed: number | null; created: number | null } } | { type: "navigate"; data: { path: VfsPath; display_path: string } } | { type: "rename"; data: { base_path: VfsPath; name: string } } | { type: "copy_move"; data: { kind: string; sources: VfsPath[]; destination: VfsPath; display_destination: string; summary: string } } | { type: "connect_remote"; data: { 
/**
 * Pre-populated transport for the dialog. Empty `Ssh { host: "" }`
 * when opened cold from the palette.
 */
initial: ConnectionKind } } | { type: "mount_sftp"; data: { host: string } } | { type: "mount_s3" } | 
/**
 * Recursive-search dialog. Opened from a pane to mount a `SearchVfs`
 * rooted at `path`. The pane navigates to the mount root on submit.
 */
{ type: "search"; data: { 
/**
 * Search root, captured from the source pane at dialog-open time.
 */
path: VfsPath; 
/**
 * Pre-rendered display label for the root (so the dialog can
 * show "Search in /home/foo" without re-resolving).
 */
display_path: string } } | { type: "mount_k8s"; data: { k8s_context: string } } | { type: "quick_connect"; data: { connections: ConnectionProfile[] } } | { type: "select_vfs"; data: { targets: VfsTarget[] } } | { type: "select_wsl_distro"; data: { distros: WslDistro[] } } | { type: "history_navigator"; data: { entries: HistoryEntryView[]; current_index: number; 
/**
 * Direction of the keypress that opened the overlay: -1 for back,
 * +1 for forward. The overlay uses this to set the initial preview
 * (one step in that direction, skipping dead entries).
 */
initial_direction: number; 
/**
 * When true, the overlay is opened as a persistent dialog: it stays
 * open until explicitly dismissed (Esc / outside-click), Alt-up does
 * not commit, blur does not abort, and per-entry delete buttons are
 * shown. When false, the overlay behaves alt-tab style (the default
 * alt-held mode).
 */
persistent: boolean } } | { type: "command_palette"; data: { category_filter: string | null } } | { type: "hot_paths" } | { type: "settings" } | { type: "confirm"; data: { message: string; action: ConfirmAction } } | { type: "user_command_input"; data: { command_index: number; command_title: string; prompts: UserCommandPrompt[]; confirms: string[] } } | { type: "debug" } | { type: "connection_log" } | { type: "about"; data: { version: string; git_revision: string | null; target_triple: string } }
export type Mode = number
export type OpenIn = "window" | "pane"
export type OperationIssueInfo = { issue_id: number; message: string; detail: string | null; actions: IssueAction[] }
export type OperationRequest = { Copy: { sources: VfsPath[]; destination: VfsPath; options?: CopyOptions } } | { Move: { sources: VfsPath[]; destination: VfsPath; options?: CopyOptions } } | { Delete: { paths: VfsPath[] } } | { SetMetadata: { paths: VfsPath[]; 
/**
 * Bits to force ON (applied as `old_mode | mode_set`)
 */
mode_set: number; 
/**
 * Bits to force OFF (applied as `old_mode & !mode_clear`)
 */
mode_clear: number; uid: number | null; gid: number | null; recursive: boolean } } | { RunCommand: { command: string; 
/**
 * VFS path, not `std::path` — crosses RPC; the executor (the
 * agent in a remote session) converts to native in its own OS.
 */
working_dir: string | null } } | 
/**
 * Synthetic long-running operation for manual testing of the progress
 * UI — scan phase, prepared totals, ticking progress, and completion.
 * Exposed only from the Debug modal in debug builds; kept here
 * unconditionally so the wire format stays identical across debug
 * and release builds.
 */
{ DebugSleep: { duration_seconds: number } }
export type OperationState = { id: number; kind: string; description: string; total_bytes: number | null; total_items: number | null; bytes_done: number; items_done: number; current_item: string; status: OperationStatus; error: string | null; issue: OperationIssueInfo | null; backgrounded: boolean; 
/**
 * Running totals from the scanning/planning phase.
 */
scanning_items: number | null; scanning_bytes: number | null }
export type OperationStatus = "scanning" | "running" | "completed" | "failed" | "cancelled" | "waiting_for_input"
export type PaneHandle = number
/**
 * A resolved keybinding after `mod+` expansion and cascading.
 */
export type ResolvedBinding = { key: string; command: string; when: string | null }
/**
 * The fully-resolved preferences state pushed to the frontend.
 */
export type ResolvedPreferences = { settings: AppPreferences; schema: JsonValue; 
/**
 * Dotted keys that are explicitly set in the user's settings file
 * (i.e. not inherited from defaults or profile).
 */
modified_keys: string[]; bindings: ResolvedBinding[]; commands: CommandInfo[]; bookmarks: BookmarkEntry[]; user_commands: UserCommandEntry[] }
export type S3Credentials = { 
/**
 * AWS access key ID (IAM user or assumed role).
 */
access_key_id: string | null; 
/**
 * AWS secret access key.
 */
secret_access_key: string | null; 
/**
 * AWS session token (for temporary credentials / AssumeRole).
 */
session_token: string | null; 
/**
 * AWS profile name (from ~/.aws/config). Overrides default profile.
 */
profile: string | null; 
/**
 * Custom endpoint URL (for S3-compatible services like MinIO, R2, etc.)
 */
endpoint_url: string | null; 
/**
 * IAM role ARN to assume. When set, uses STS AssumeRole with the
 * ambient or explicit credentials, then mounts with the resulting
 * temporary credentials.
 */
role_arn: string | null; 
/**
 * External ID for AssumeRole (optional, for cross-account access).
 */
external_id: string | null }
export type SearchMatch = { offset: number; length: number }
export type SearchPattern = { Literal: number[] } | { Regex: string }
export type Sorting = { key: SortingKey; asc: boolean }
export type SortingKey = "name" | "extension" | "size" | "user" | "mode" | "group" | "modified" | "accessed" | "created"
export type SshHostEntry = { host: string; hostname: string | null; user: string | null }
export type TerminalHandle = number
export type ThemeMode = "system" | "light" | "dark"
/**
 * A single `[[command]]` entry in the TOML file.
 */
export type UserCommandEntry = { title: string; run: string; key?: string | null; terminal?: boolean; 
/**
 * Run-context filter — which file selection state allows this command
 * to appear in the palette / be invoked. One of "file", "directory",
 * "selection", or absent (= any). NOT to be confused with `[[bind]].when`,
 * which is the keybinding *dispatch* context.
 */
applies_to?: string | null }
export type UserCommandPrompt = { label: string; default: string }
export type UserGroup = { name: string } | { id: number }
export type VfsId = number
/**
 * A fully-qualified location: which VFS, and where within it.
 * 
 * `specta::Type` is derived: `PathBuf`'s own `Type` impl renders as a
 * plain `string`, so the generated TS is `{ vfs_id: VfsId; path: string }`
 * under the named type `VfsPath` — identical to the pre-refactor shape.
 */
export type VfsPath = { vfs_id: VfsId; path: string }
/**
 * Free-schema progress snapshot. The frontend renders this as a short
 * inline status line — `"<stage> · <processed>/<total> · <extra>"` —
 * in the active pane's status bar.
 */
export type VfsProgress = { 
/**
 * Short verb-phrase like "Searching" or "Indexing".
 */
stage: string; 
/**
 * Dominant counter — running count when `total` is `None`,
 * determinate progress when both are set.
 */
processed: number | null; total: number | null; 
/**
 * Sidecar values (e.g. `"hits" → "42"`). Surface as
 * `" · key: value"` suffixes. The producer chooses keys; nothing
 * in the pipeline parses them.
 */
extra: Partial<{ [key in string]: string }> }
export type VfsTarget = { vfs_id: VfsId | null; type_name: string; display_name: string; 
/**
 * Human-readable label for a mounted instance (e.g. hostname for
 * SFTP, or the drive for a split-root entry).
 */
label: string | null; 
/**
 * Dialog to open when user selects this unmounted VFS type.
 * If None and vfs_id is None, the type supports auto-mount.
 */
mount_dialog: string | null; 
/**
 * Specific root to land on. `Some` only for split-root VFSes
 * (one target per drive); selecting it navigates straight there
 * instead of the VFS's default `initial_path`.
 */
root: string | null }
/**
 * Display mode for the file viewer. Wire format is snake_case to match
 * the strings the frontend uses.
 */
export type ViewerMode = "text" | "hex" | "image" | "audio" | "video" | "pdf"
/**
 * One installed WSL distribution. Serialized into the picker modal payload.
 */
export type WslDistro = { name: string; is_default: boolean }

/** tauri-specta globals **/

import {
	invoke as TAURI_INVOKE,
	Channel as TAURI_CHANNEL,
} from "@tauri-apps/api/core";
import * as TAURI_API_EVENT from "@tauri-apps/api/event";
import { type WebviewWindow as __WebviewWindow__ } from "@tauri-apps/api/webviewWindow";

type __EventObj__<T> = {
	listen: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.listen<T>>;
	once: (
		cb: TAURI_API_EVENT.EventCallback<T>,
	) => ReturnType<typeof TAURI_API_EVENT.once<T>>;
	emit: null extends T
		? (payload?: T) => ReturnType<typeof TAURI_API_EVENT.emit>
		: (payload: T) => ReturnType<typeof TAURI_API_EVENT.emit>;
};

export type Result<T, E> =
	| { status: "ok"; data: T }
	| { status: "error"; error: E };

function __makeEvents__<T extends Record<string, any>>(
	mappings: Record<keyof T, string>,
) {
	return new Proxy(
		{} as unknown as {
			[K in keyof T]: __EventObj__<T[K]> & {
				(handle: __WebviewWindow__): __EventObj__<T[K]>;
			};
		},
		{
			get: (_, event) => {
				const name = mappings[event as keyof T];

				return new Proxy((() => {}) as any, {
					apply: (_, __, [window]: [__WebviewWindow__]) => ({
						listen: (arg: any) => window.listen(name, arg),
						once: (arg: any) => window.once(name, arg),
						emit: (arg: any) => window.emit(name, arg),
					}),
					get: (_, command: keyof __EventObj__<any>) => {
						switch (command) {
							case "listen":
								return (arg: any) => TAURI_API_EVENT.listen(name, arg);
							case "once":
								return (arg: any) => TAURI_API_EVENT.once(name, arg);
							case "emit":
								return (arg: any) => TAURI_API_EVENT.emit(name, arg);
						}
					},
				});
			},
		},
	);
}
