/// Static command definitions — the source of truth for all commands.
#[derive(Debug, Clone)]
pub struct CommandDef {
    pub id: String,
    pub name: String,
    pub short_name: Option<String>,
    pub category: String,
    pub default_key: Option<String>,
    pub default_when: Option<String>,
    pub needs_pane: bool,
}

/// Like `vec![]` but supports `@if(expr) { ... }` blocks for
/// runtime-conditional items and `@cfg(pred) { ... }` blocks for
/// compile-time conditional items.
macro_rules! conditional_vec {
    (@inner $v:ident,) => {};
    // @cfg(pred) { items... }, rest...
    (@inner $v:ident, @cfg($pred:meta) { $($item:expr),* $(,)? } $($rest:tt)*) => {
        $(
            #[cfg($pred)]
            $v.push($item);
        )*
        conditional_vec!(@inner $v, $($rest)*);
    };
    // @if(expr) { items... }, rest...
    (@inner $v:ident, @if($cond:expr) { $($item:expr),* $(,)? } $($rest:tt)*) => {
        if $cond {
            $( $v.push($item); )*
        }
        conditional_vec!(@inner $v, $($rest)*);
    };
    // regular item, rest...
    (@inner $v:ident, $item:expr, $($rest:tt)*) => {
        $v.push($item);
        conditional_vec!(@inner $v, $($rest)*);
    };
    // entry point
    ($($body:tt)*) => {{
        let mut v: Vec<_> = Vec::with_capacity(64);
        conditional_vec!(@inner v, $($body)*);
        v
    }};
}

pub fn default_commands() -> Vec<CommandDef> {
    conditional_vec![
        CommandDef {
            id: "new_window".into(),
            name: "New Window".into(),
            short_name: None,
            category: "File".into(),
            default_key: Some("mod+n".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "as_other_pane".into(),
            name: "As Other Pane".into(),
            short_name: None,
            category: "Navigation".into(),
            default_key: Some("mod+.".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "open_in_left_pane".into(),
            name: "Open in Left Pane".into(),
            short_name: None,
            category: "Navigation".into(),
            default_key: Some("mod+left".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "open_in_right_pane".into(),
            name: "Open in Right Pane".into(),
            short_name: None,
            category: "Navigation".into(),
            default_key: Some("mod+right".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "select_all".into(),
            name: "Select All".into(),
            short_name: None,
            category: "Selection".into(),
            default_key: Some("mod+a".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "deselect_all".into(),
            name: "Clear Selection".into(),
            short_name: None,
            category: "Selection".into(),
            default_key: Some("mod+d".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "view".into(),
            name: "View".into(),
            short_name: None,
            category: "File".into(),
            default_key: Some("f3".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "edit".into(),
            name: "Edit".into(),
            short_name: None,
            category: "File".into(),
            default_key: Some("f4".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "rename".into(),
            name: "Rename...".into(),
            short_name: Some("Rename".into()),
            category: "File".into(),
            default_key: Some("f2".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "properties".into(),
            name: "File Properties...".into(),
            short_name: Some("Props".into()),
            category: "File".into(),
            default_key: Some("alt+enter".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "delete_selected".into(),
            name: "Delete Selected".into(),
            short_name: Some("Delete".into()),
            category: "File".into(),
            default_key: Some("f8".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "create_directory".into(),
            name: "Create Directory...".into(),
            short_name: Some("MkDir".into()),
            category: "File".into(),
            default_key: Some("f7".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "create_file".into(),
            name: "Create File...".into(),
            short_name: Some("MkFile".into()),
            category: "File".into(),
            default_key: None,
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "create_and_edit".into(),
            name: "Create and Edit File...".into(),
            short_name: Some("New+Edit".into()),
            category: "File".into(),
            default_key: Some("shift+f4".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "navigate".into(),
            name: "Go To...".into(),
            short_name: Some("Go To".into()),
            category: "Navigation".into(),
            default_key: Some("mod+l".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "open".into(),
            name: "Open in Default App".into(),
            short_name: Some("Open".into()),
            category: "File".into(),
            default_key: None,
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "follow_symlink".into(),
            name: "Follow Symlink".into(),
            short_name: None,
            category: "Navigation".into(),
            default_key: Some("shift+enter".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "navigate_back".into(),
            name: "Navigate Back".into(),
            short_name: Some("Back".into()),
            category: "Navigation".into(),
            default_key: Some("alt+left".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "navigate_forward".into(),
            name: "Navigate Forward".into(),
            short_name: Some("Forward".into()),
            category: "Navigation".into(),
            default_key: Some("alt+right".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "send_to_terminal".into(),
            name: "Open in Terminal".into(),
            short_name: Some("Terminal".into()),
            category: "Terminal".into(),
            default_key: Some("mod+enter".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "copy".into(),
            name: "Copy to Other Pane...".into(),
            short_name: Some("Copy".into()),
            category: "File".into(),
            default_key: Some("f5".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "move".into(),
            name: "Move to Other Pane...".into(),
            short_name: Some("Move".into()),
            category: "File".into(),
            default_key: Some("f6".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "copy_to_clipboard".into(),
            name: "Copy Path to Clipboard".into(),
            short_name: Some("CopyPath".into()),
            category: "Edit".into(),
            default_key: Some("mod+c".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "paste_from_clipboard".into(),
            name: "Paste Path from Clipboard".into(),
            short_name: Some("PastePath".into()),
            category: "Edit".into(),
            default_key: Some("mod+v".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "toggle_hidden".into(),
            name: "Toggle Hidden Files".into(),
            short_name: Some("Hidden".into()),
            category: "View".into(),
            default_key: Some("mod+h".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "close_window".into(),
            name: "Close Window".into(),
            short_name: Some("Close".into()),
            category: "File".into(),
            default_key: Some("mod+w".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "refresh".into(),
            name: "Refresh File List".into(),
            short_name: Some("Refresh".into()),
            category: "View".into(),
            default_key: None,
            default_when: None,
            needs_pane: true,
        },
        CommandDef {
            id: "quick_connect".into(),
            name: "Quick Connect...".into(),
            short_name: Some("Connect".into()),
            category: "File".into(),
            default_key: Some("ctrl+r".into()),
            default_when: None,
            needs_pane: true,
        },
        CommandDef {
            id: "connect_remote".into(),
            name: "Connect to Remote Host...".into(),
            short_name: Some("Remote".into()),
            category: "File".into(),
            default_key: Some("mod+shift+r".into()),
            default_when: None,
            needs_pane: false,
        },
        @cfg(target_os = "linux") {
            CommandDef {
                id: "open_elevated".into(),
                name: "Open Elevated".into(),
                short_name: None,
                category: "File".into(),
                default_key: None,
                default_when: None,
                needs_pane: false,
            },
        }
        CommandDef {
            id: "select_vfs".into(),
            name: "Select Filesystem".into(),
            short_name: Some("VFS".into()),
            category: "Navigation".into(),
            default_key: Some("mod+shift+l".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "mount_s3".into(),
            name: "Mount S3".into(),
            short_name: None,
            category: "Navigation".into(),
            default_key: None,
            default_when: None,
            needs_pane: true,
        },
        CommandDef {
            id: "mount_sftp".into(),
            name: "Mount SFTP...".into(),
            short_name: Some("SFTP".into()),
            category: "Navigation".into(),
            default_key: None,
            default_when: None,
            needs_pane: true,
        },
        CommandDef {
            id: "unmount_vfs".into(),
            name: "Disconnect VFS".into(),
            short_name: None,
            category: "Navigation".into(),
            default_key: None,
            default_when: None,
            needs_pane: true,
        },
        CommandDef {
            id: "open_folder".into(),
            name: "Open Folder in Default File Manager".into(),
            short_name: Some("Reveal".into()),
            category: "File".into(),
            default_key: Some("shift+f3".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "toggle_terminal_panel".into(),
            name: "Toggle Terminal".into(),
            short_name: None,
            category: "Terminal".into(),
            default_key: Some("ctrl+`".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "focus_panes".into(),
            name: "Focus File Panes".into(),
            short_name: Some("Panes".into()),
            category: "Navigation".into(),
            default_key: Some("alt+up".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "focus_terminal".into(),
            name: "Focus Terminal".into(),
            short_name: Some("Terminal".into()),
            category: "Navigation".into(),
            default_key: Some("alt+down".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "create_terminal".into(),
            name: "New Terminal".into(),
            short_name: None,
            category: "Terminal".into(),
            default_key: Some("ctrl+shift+~".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "next_terminal".into(),
            name: "Next Terminal".into(),
            short_name: None,
            category: "Terminal".into(),
            default_key: Some("ctrl+pagedown".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "prev_terminal".into(),
            name: "Previous Terminal".into(),
            short_name: None,
            category: "Terminal".into(),
            default_key: Some("ctrl+pageup".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "open_settings".into(),
            name: "Open Settings".into(),
            short_name: Some("Settings".into()),
            category: "File".into(),
            default_key: Some("mod+,".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "command_palette".into(),
            name: "Command Palette".into(),
            short_name: Some("CmdPalette".into()),
            category: "View".into(),
            default_key: Some("mod+shift+p".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "hot_paths".into(),
            name: "Hot Paths".into(),
            short_name: None,
            category: "Navigation".into(),
            default_key: Some("mod+p".into()),
            default_when: None,
            needs_pane: false,
        },
        CommandDef {
            id: "user_commands".into(),
            name: "User Commands".into(),
            short_name: None,
            category: "View".into(),
            default_key: Some("f9".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "add_bookmark".into(),
            name: "Add Current Path to Bookmarks".into(),
            short_name: Some("Bookmark".into()),
            category: "Navigation".into(),
            default_key: Some("mod+b".into()),
            default_when: Some("pane_focused".into()),
            needs_pane: true,
        },
        CommandDef {
            id: "connection_log".into(),
            name: "Connection Log".into(),
            short_name: None,
            category: "View".into(),
            default_key: None,
            default_when: None,
            needs_pane: false,
        },
        @if(cfg!(debug_assertions)) {
            CommandDef {
                id: "debug".into(),
                name: "Debug".into(),
                short_name: None,
                category: "View".into(),
                default_key: None,
                default_when: None,
                needs_pane: false,
            },
        }
    ]
}
