import { useEffect, useRef } from "react";
import * as Dialog from "@radix-ui/react-dialog";
import { safe } from "../../lib/ipc";
import { commands } from "../../lib/bindings";
import { DialogShell, DialogHeader, DialogFooter } from "./primitives";
import styles from "./ThirdPartyNotices.module.scss";
// Generated by `cargo xtask notices`; bundled as text so the notices ship
// inside the app shell rather than being read off disk at runtime.
import notices from "../../../THIRD-PARTY-NOTICES.md?raw";

const preventAutoFocus = (e: Event) => e.preventDefault();

export default function ThirdPartyNoticesContent() {
  // The scroller takes focus, not the Close button: the document is long and
  // Page/arrow keys have to work the moment it opens.
  const ref = useRef<HTMLPreElement>(null);
  useEffect(() => ref.current?.focus(), []);

  return (
    <Dialog.Content
      className={styles.content}
      onCloseAutoFocus={preventAutoFocus}
    >
      <DialogShell>
        <DialogHeader
          title="Third-Party Notices"
          summary="Newt is distributed with these components, each under its own licence."
        />
        <pre className={styles.notices} ref={ref} tabIndex={0}>
          {notices}
        </pre>
        <DialogFooter>
          <button type="button" onClick={() => safe(commands.closeModal())}>
            Close
          </button>
        </DialogFooter>
      </DialogShell>
    </Dialog.Content>
  );
}
